# Generated by Django 4.2.30 on 2026-07-27 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
